language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-adf-widget' ]; then cd .. && eval "mv $currentfolder generator-adf-widget" && cd generator-adf-widget; fi
